version: 1.1.1
pipeline_os: windows
create_pr_release_to_master: true

env:
  - GITHUB_ACCESS_TOKEN_ID: github_access_token_acsbuildguy
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - JENKINS_NODE_WIN: CDA-VS22-DT

code_analysis:
  sonarqube:
    source_encoding: UTF-8
    src: .
    useCommonSonar: true
    coverage_reports:
      - coverage.info

build:
  -
    scripts:
      - dotnet msbuild DynamoPythonNet3.sln -p:Configuration=Release -restore
      
ci_test:
  tests:
    -
      scripts:
        - dotnet test

deployment:
  -
    type: sign
    files_to_sign:
      - package_output/DSPythonNet3/**/DSPythonNet3*.dll
      - package_output/DSPythonNet3/**/Python.*.dll
  -
    type: customized
    scripts:
      - "pwsh.exe -ExecutionPolicy ByPass -Command Compress-Archive -Path package_output/DSPythonNet3/* -DestinationPath DSPythonNet3.zip"
  -
    type: artifacts
    publish_to_jenkins: true
    publish_to_artifactory: false
    publish_to_package_manager: true
    use_dev_pm: false
    outputs:
      - DSPythonNet3.zip
